// this file is autogenerated from the wheels described in ../package.json
export const allJSONUrl = "https://cdn.jsdelivr.net/npm/@jupyterlite/pyodide-kernel@0.5.2/pypi/all.json";
export const ipykernelWheelUrl = "https://cdn.jsdelivr.net/npm/@jupyterlite/pyodide-kernel@0.5.2/pypi/ipykernel-6.9.2-py3-none-any.whl";
export const pipliteWheelUrl = "https://cdn.jsdelivr.net/npm/@jupyterlite/pyodide-kernel@0.5.2/pypi/piplite-0.6.0a5-py3-none-any.whl";
export const pyodide_kernelWheelUrl = "https://cdn.jsdelivr.net/npm/@jupyterlite/pyodide-kernel@0.5.2/pypi/pyodide_kernel-0.6.0a5-py3-none-any.whl";
export const widgetsnbextensionWheelUrl = "https://cdn.jsdelivr.net/npm/@jupyterlite/pyodide-kernel@0.5.2/pypi/widgetsnbextension-3.6.999-py3-none-any.whl";
export const widgetsnbextensionWheelUrl1 = "https://cdn.jsdelivr.net/npm/@jupyterlite/pyodide-kernel@0.5.2/pypi/widgetsnbextension-4.0.999-py3-none-any.whl";
