name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
          
      - name: Verify installations
        run: |
          deno --version
          python3 --version
          pip --version
        
      - name: Install Python build dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install hatch build wheel
        
      - name: Generate Python wheels
        run: |
          cd kernel
          python3 generate-wheels-js.py
        
      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-
            
      - name: Install dependencies
        run: deno cache --lock=deno.lock mod.ts
        
      - name: Run tests
        run: deno test --allow-all --coverage=coverage
        
      - name: Generate coverage report
        run: deno coverage coverage --lcov --output=coverage.lcov
        
      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.lcov
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false 